use mongo_tmp_tubobo_express;
create table appointtaskentity
(
id                          String            
,taskNo                      String    
,taskType                   String     
,normalUserId           String           
,store                  map<string,string>
,operator               map<string,string>
,wayBillS                    map<string,string>
,wayBillR                    map<string,string>
,senderName            String        
,senderPhone            String           
,senderPcdCode           String           
,senderPcdName           String           
,senderAddress            String           
,receiverName            String           
,receiverPhone            String           
,receiverPcdCode       String           
,receiverPcdName       String           
,receiverAddress           String           
,appointTime        String           
,appointTimeType       String           
,finishTime            Timestamp       
,shipment            String           
,insureFlag            String           
,insurePrice        String           
,weight             String           
,size             String           
,source                   String     
,remark             String           
,bigPackage            String           
,payment         String           
,payFreight            String           
,evaluationFlag           String           
,delFlag                     String            
,createDate               Timestamp   
,createBy             String           
,updateDate         Timestamp       
,updateBy          String            
,senderAddressProvince       String            
,senderAddressCity           String            
,senderAddressDistrict       String            
,senderAddressStreet         String            
,senderAddressRoomNo         String            
,senderAddressDetail         String            
,receiverAddressProvince     String            
,receiverAddressCity         String            
,receiverAddressDistrict     String            
,receiverAddressStreet       String            
,receiverAddressRoomNo       String            
,receiverAddressDetail       String            
,senderLongitude             String            
,senderLatitude              String            
,receiverLongitude           String            
,receiverLatitude            String            
,deliveryDistance       String            
,pickUpDistance        String            
,orderTime      Timestamp         
,acceptTime         Timestamp         
,pickTime      Timestamp         
,cancelTime         Timestamp         
,peekOverFee     String            
,weatherOverFee        String            
,platformSubsidyFee       String            
,bigParcelFee     String            
,payDoor      String            
,payDistribution    String            
,cancelCompensation    String            
,cancelFine            String            
,cancelReason              String            
,sendStatus         String            
,sendType         String            
,sendCode         String            
,distributionStatus       String            
,distributionType       String            
,pickupCode         String            
,areaNum      String            
,paidFlag         String            
,refundFlag         String            
,printFlag         String            
,commonFlag         String            
,riderFlag         String            
,payId          String            
,expressCompanyId       String            
,senderAdcode        String            
,cityCode         String
)
ROW FORMAT SERDE "com.mongodb.hadoop.hive.BSONSerDe"
WITH SERDEPROPERTIES('mongo.columns.mapping'='{"id":"_id","taskNo":"taskNo","taskType":"taskType","normalUserId":"normalUserId","store":"store","operator":"operator","wayBillS":"wayBillS","wayBillR":"wayBillR","senderName":"senderName","senderPhone":"senderPhone","senderPcdCode":"senderPcdCode","senderPcdName":"senderPcdName","senderAddress":"senderAddress","receiverName":"receiverName","receiverPhone":"receiverPhone","receiverPcdCode":"receiverPcdCode","receiverPcdName":"receiverPcdName","receiverAddress":"receiverAddress","appointTime":"appointTime","appointTimeType":"appointTimeType","finishTime":"finishTime","shipment":"shipment","insureFlag":"insureFlag","insurePrice":"insurePrice","weight":"weight","size":"size","source":"source","remark":"remark","bigPackage":"bigPackage","payment":"payment","payFreight":"payFreight","evaluationFlag":"evaluationFlag","delFlag":"delFlag","createDate":"createDate","createBy":"createBy","updateDate":"updateDate","updateBy":"updateBy","senderAddressProvince":"senderAddressProvince","senderAddressCity":"senderAddressCity","senderAddressDistrict":"senderAddressDistrict","senderAddressStreet":"senderAddressStreet","senderAddressRoomNo":"senderAddressRoomNo","senderAddressDetail":"senderAddressDetail","receiverAddressProvince":"receiverAddressProvince","receiverAddressCity":"receiverAddressCity","receiverAddressDistrict":"receiverAddressDistrict","receiverAddressStreet":"receiverAddressStreet","receiverAddressRoomNo":"receiverAddressRoomNo","receiverAddressDetail":"receiverAddressDetail","senderLongitude":"senderLongitude","senderLatitude":"senderLatitude","receiverLongitude":"receiverLongitude","receiverLatitude":"receiverLatitude","deliveryDistance":"deliveryDistance","pickUpDistance":"pickUpDistance","orderTime":"orderTime","acceptTime":"acceptTime","pickTime":"pickTime","cancelTime":"cancelTime","peekOverFee":"peekOverFee","weatherOverFee":"weatherOverFee","platformSubsidyFee":"platformSubsidyFee","bigParcelFee":"bigParcelFee","payDoor":"payDoor","payDistribution":"payDistribution","cancelCompensation":"cancelCompensation","cancelFine":"cancelFine","cancelReason":"cancelReason","sendStatus":"sendStatus","sendType":"sendType","sendCode":"sendCode","distributionStatus":"distributionStatus","distributionType":"distributionType","pickupCode":"pickupCode","areaNum":"areaNum","paidFlag":"paidFlag","refundFlag":"refundFlag","printFlag":"printFlag","commonFlag":"commonFlag","riderFlag":"riderFlag","payId":"payId","expressCompanyId":"expressCompanyId","senderAdcode":"senderAdcode","cityCode":"cityCode"}')
STORED AS INPUTFORMAT "com.mongodb.hadoop.mapred.BSONFileInputFormat"
OUTPUTFORMAT "com.mongodb.hadoop.hive.output.HiveBSONFileOutputFormat"
location '/apps/hive/warehouse/tubobo_express.mongo/AppointTaskEntity/';
