create database IF NOT EXISTS tubobo_reportdata;
use tubobo_reportdata; 
create table tubobo_reportdata.express_appointment_order_status_info
(
create_time                  string comment "创建时间",   
Province                     string comment "订单省份",
City                         string comment "订单城市",
create_order                 string comment "创建订单量",
big_bag                      string comment "大件包裹",
common_bag                   string comment "普通包裹",
init_order                   string comment "初始化,待支付状态",
cancel_order                 string comment "取消订单状态",
waiting_grab_order           string comment "待接单状态",
waiting_pick_order           string comment "待取货状态",
deliverying_order            string comment "配送中状态",
close_order                  string comment "关闭订单状态",
finish_order                 string comment "完成订单状态",
other_order                  string comment "其他订单状态",
grab_overtime_cancel         string comment "超时未接单取消",
grab_sender_cancel           string comment "未接单时用户主动取消",
pay_overtime_cancel          string comment "支付超时取消",
admin_cancel                 string comment "后台取消",
pay_sender_cancel            string comment "未支付主动取消",
pick_rider_cancel            string comment "骑手主动取消",
store_cancel                 string comment "门店主动取消",
other_cancel                 string comment "其他取消"
)
comment '预约配送订单状态表'
partitioned by (day string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS TEXTFILE;


use ds_tubobo_express;
create table bas_appointtaskentity_pd
(
id                          String              comment "序列ID",
taskNo                      String              comment "任务编码",
taskType                    String              comment "任务类型:寄件任务,配送任务",
normalUserId                String              comment "用户ID",
store                       map<string,string>  comment "门店",
operator                    map<string,string>  comment "任务归属人",
wayBillS                    map<string,string>  comment "",
wayBillR                    map<string,string>  comment "",
senderName                  String              comment "寄件人姓名",
senderPhone                 String              comment "寄件人手机号",
senderPcdCode               String              comment "省市区代码",
senderPcdName               String              comment "省市区中文",
senderAddress               String              comment "寄件人详细地址",
receiverName                String              comment "收件人姓名",
receiverPhone               String              comment "收件人手机号",
receiverPcdCode             String              comment "省市区代码",
receiverPcdName             String              comment "省市区中文",
receiverAddress             String              comment "收件人详细地址",
appointTime                 String              comment "预约时间",
appointTimeType             String              comment "0,立即,1,今天,2,明天,3,后天",
finishTime                  Timestamp           comment "任务完成时间",
shipment                    String              comment "寄件类型",
insureFlag                  String              comment "是否保价",
insurePrice                 String              comment "保价金额 单位:元:数字",
weight                      String              comment "单位:KG:数字",
size                        String              comment "物品大小",
source                      String              comment "来源",
remark                      String              comment "备注",
bigPackage                  String              comment "是否大件",
payment                     String              comment "代收货款",
payFreight                  String              comment "代收运费",
evaluationFlag              String              comment "是否评价",
delFlag                     String              comment "",
createDate                  Timestamp           comment "录入时间",
createBy                    String              comment "录入人ID",
updateDate                  Timestamp           comment "更新时间",
updateBy                    String              comment "更新人ID",
senderAddressProvince       String              comment "发件人省份",
senderAddressCity           String              comment "发件人城市",
senderAddressDistrict       String              comment "发件人区域",
senderAddressStreet         String              comment "发件人街道",
senderAddressRoomNo         String              comment "发件人房间号",
senderAddressDetail         String              comment "发件人详细地址",
receiverAddressProvince     String              comment "收件人省份",
receiverAddressCity         String              comment "收件人城市",
receiverAddressDistrict     String              comment "收件人区域",
receiverAddressStreet       String              comment "收件人街道",
receiverAddressRoomNo       String              comment "收件人房间号",
receiverAddressDetail       String              comment "收件人详情地址",
senderLongitude             String              comment "发件人经度",
senderLatitude              String              comment "发件人纬度",
receiverLongitude           String              comment "收件人经度",
receiverLatitude            String              comment "收件人纬度",
deliveryDistance            String              comment "送货距离",
pickUpDistance              String              comment "取货距离",
orderTime                   Timestamp           comment "下单时间",
acceptTime                  Timestamp           comment "接单时间",
pickTime                    Timestamp           comment "取货时间",
cancelTime                  Timestamp           comment "取消时间",
peekOverFee                 String              comment "高峰溢价费",
weatherOverFee              String              comment "天气溢价费",
platformSubsidyFee          String              comment "平台补贴费",
bigParcelFee                String              comment "大件包裹费用",
payDoor                     String              comment "上门费用",
payDistribution             String              comment "配送费用",
cancelCompensation          String              comment "订单取消赔付",
cancelFine                  String              comment "订单取消罚款",
cancelReason                String              comment "订单取消原因",
sendStatus                  String              comment "寄件状态",
sendType                    String              comment "寄件类型",
sendCode                    String              comment "寄件码",
distributionStatus          String              comment "配送状态:初始化:待接单:待取货:配送中:已完成:已取消:",
distributionType            String              comment "配送类型:自提,配送",
pickupCode                  String              comment "取货码",
areaNum                     String              comment "取件号-waybillSEntity",
paidFlag                    String              comment "是否支付",
refundFlag                  String              comment "是否退款",
printFlag                   String              comment "是否打印",
commonFlag                  String              comment "是否流到众包",
riderFlag                   String              comment "是否社区骑手接单:true-社区骑手:false-PDA",
payId                       String              comment "支付ID",
expressCompanyId            String              comment "快递公司ID",
senderAdcode                String              comment "发送者区域码",
cityCode                    String              comment "城市Code"
)
comment '预约配送详情表'
partitioned by (day string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS RCFILE;

create table bas_appointtaskentity_init
(
id                          String              comment "序列ID",
taskNo                      String              comment "任务编码",
taskType                    String              comment "任务类型:寄件任务,配送任务",
normalUserId                String              comment "用户ID",
store                       map<string,string>  comment "门店",
operator                    map<string,string>  comment "任务归属人",
wayBillS                    map<string,string>  comment "",
wayBillR                    map<string,string>  comment "",
senderName                  String              comment "寄件人姓名",
senderPhone                 String              comment "寄件人手机号",
senderPcdCode               String              comment "省市区代码",
senderPcdName               String              comment "省市区中文",
senderAddress               String              comment "寄件人详细地址",
receiverName                String              comment "收件人姓名",
receiverPhone               String              comment "收件人手机号",
receiverPcdCode             String              comment "省市区代码",
receiverPcdName             String              comment "省市区中文",
receiverAddress             String              comment "收件人详细地址",
appointTime                 String              comment "预约时间",
appointTimeType             String              comment "0,立即,1,今天,2,明天,3,后天",
finishTime                  Timestamp           comment "任务完成时间",
shipment                    String              comment "寄件类型",
insureFlag                  String              comment "是否保价",
insurePrice                 String              comment "保价金额 单位:元:数字",
weight                      String              comment "单位:KG:数字",
size                        String              comment "物品大小",
source                      String              comment "来源",
remark                      String              comment "备注",
bigPackage                  String              comment "是否大件",
payment                     String              comment "代收货款",
payFreight                  String              comment "代收运费",
evaluationFlag              String              comment "是否评价",
delFlag                     String              comment "",
createDate                  Timestamp           comment "录入时间",
createBy                    String              comment "录入人ID",
updateDate                  Timestamp           comment "更新时间",
updateBy                    String              comment "更新人ID",
senderAddressProvince       String              comment "发件人省份",
senderAddressCity           String              comment "发件人城市",
senderAddressDistrict       String              comment "发件人区域",
senderAddressStreet         String              comment "发件人街道",
senderAddressRoomNo         String              comment "发件人房间号",
senderAddressDetail         String              comment "发件人详细地址",
receiverAddressProvince     String              comment "收件人省份",
receiverAddressCity         String              comment "收件人城市",
receiverAddressDistrict     String              comment "收件人区域",
receiverAddressStreet       String              comment "收件人街道",
receiverAddressRoomNo       String              comment "收件人房间号",
receiverAddressDetail       String              comment "收件人详情地址",
senderLongitude             String              comment "发件人经度",
senderLatitude              String              comment "发件人纬度",
receiverLongitude           String              comment "收件人经度",
receiverLatitude            String              comment "收件人纬度",
deliveryDistance            String              comment "送货距离",
pickUpDistance              String              comment "取货距离",
orderTime                   Timestamp           comment "下单时间",
acceptTime                  Timestamp           comment "接单时间",
pickTime                    Timestamp           comment "取货时间",
cancelTime                  Timestamp           comment "取消时间",
peekOverFee                 String              comment "高峰溢价费",
weatherOverFee              String              comment "天气溢价费",
platformSubsidyFee          String              comment "平台补贴费",
bigParcelFee                String              comment "大件包裹费用",
payDoor                     String              comment "上门费用",
payDistribution             String              comment "配送费用",
cancelCompensation          String              comment "订单取消赔付",
cancelFine                  String              comment "订单取消罚款",
cancelReason                String              comment "订单取消原因",
sendStatus                  String              comment "寄件状态",
sendType                    String              comment "寄件类型",
sendCode                    String              comment "寄件码",
distributionStatus          String              comment "配送状态:初始化:待接单:待取货:配送中:已完成:已取消:",
distributionType            String              comment "配送类型:自提,配送",
pickupCode                  String              comment "取货码",
areaNum                     String              comment "取件号-waybillSEntity",
paidFlag                    String              comment "是否支付",
refundFlag                  String              comment "是否退款",
printFlag                   String              comment "是否打印",
commonFlag                  String              comment "是否流到众包",
riderFlag                   String              comment "是否社区骑手接单:true-社区骑手:false-PDA",
payId                       String              comment "支付ID",
expressCompanyId            String              comment "快递公司ID",
senderAdcode                String              comment "发送者区域码",
cityCode                    String              comment "城市Code"
)
comment '预约配送详情表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS RCFILE;

create table bas_appointtaskentity_idld
(
id                          String              comment "序列ID",
taskNo                      String              comment "任务编码",
taskType                    String              comment "任务类型:寄件任务,配送任务",
normalUserId                String              comment "用户ID",
store                       map<string,string>  comment "门店",
operator                    map<string,string>  comment "任务归属人",
wayBillS                    map<string,string>  comment "",
wayBillR                    map<string,string>  comment "",
senderName                  String              comment "寄件人姓名",
senderPhone                 String              comment "寄件人手机号",
senderPcdCode               String              comment "省市区代码",
senderPcdName               String              comment "省市区中文",
senderAddress               String              comment "寄件人详细地址",
receiverName                String              comment "收件人姓名",
receiverPhone               String              comment "收件人手机号",
receiverPcdCode             String              comment "省市区代码",
receiverPcdName             String              comment "省市区中文",
receiverAddress             String              comment "收件人详细地址",
appointTime                 String              comment "预约时间",
appointTimeType             String              comment "0,立即,1,今天,2,明天,3,后天",
finishTime                  Timestamp           comment "任务完成时间",
shipment                    String              comment "寄件类型",
insureFlag                  String              comment "是否保价",
insurePrice                 String              comment "保价金额 单位:元:数字",
weight                      String              comment "单位:KG:数字",
size                        String              comment "物品大小",
source                      String              comment "来源",
remark                      String              comment "备注",
bigPackage                  String              comment "是否大件",
payment                     String              comment "代收货款",
payFreight                  String              comment "代收运费",
evaluationFlag              String              comment "是否评价",
delFlag                     String              comment "",
createDate                  Timestamp           comment "录入时间",
createBy                    String              comment "录入人ID",
updateDate                  Timestamp           comment "更新时间",
updateBy                    String              comment "更新人ID",
senderAddressProvince       String              comment "发件人省份",
senderAddressCity           String              comment "发件人城市",
senderAddressDistrict       String              comment "发件人区域",
senderAddressStreet         String              comment "发件人街道",
senderAddressRoomNo         String              comment "发件人房间号",
senderAddressDetail         String              comment "发件人详细地址",
receiverAddressProvince     String              comment "收件人省份",
receiverAddressCity         String              comment "收件人城市",
receiverAddressDistrict     String              comment "收件人区域",
receiverAddressStreet       String              comment "收件人街道",
receiverAddressRoomNo       String              comment "收件人房间号",
receiverAddressDetail       String              comment "收件人详情地址",
senderLongitude             String              comment "发件人经度",
senderLatitude              String              comment "发件人纬度",
receiverLongitude           String              comment "收件人经度",
receiverLatitude            String              comment "收件人纬度",
deliveryDistance            String              comment "送货距离",
pickUpDistance              String              comment "取货距离",
orderTime                   Timestamp           comment "下单时间",
acceptTime                  Timestamp           comment "接单时间",
pickTime                    Timestamp           comment "取货时间",
cancelTime                  Timestamp           comment "取消时间",
peekOverFee                 String              comment "高峰溢价费",
weatherOverFee              String              comment "天气溢价费",
platformSubsidyFee          String              comment "平台补贴费",
bigParcelFee                String              comment "大件包裹费用",
payDoor                     String              comment "上门费用",
payDistribution             String              comment "配送费用",
cancelCompensation          String              comment "订单取消赔付",
cancelFine                  String              comment "订单取消罚款",
cancelReason                String              comment "订单取消原因",
sendStatus                  String              comment "寄件状态",
sendType                    String              comment "寄件类型",
sendCode                    String              comment "寄件码",
distributionStatus          String              comment "配送状态:初始化:待接单:待取货:配送中:已完成:已取消:",
distributionType            String              comment "配送类型:自提,配送",
pickupCode                  String              comment "取货码",
areaNum                     String              comment "取件号-waybillSEntity",
paidFlag                    String              comment "是否支付",
refundFlag                  String              comment "是否退款",
printFlag                   String              comment "是否打印",
commonFlag                  String              comment "是否流到众包",
riderFlag                   String              comment "是否社区骑手接单:true-社区骑手:false-PDA",
payId                       String              comment "支付ID",
expressCompanyId            String              comment "快递公司ID",
senderAdcode                String              comment "发送者区域码",
cityCode                    String              comment "城市Code"
)
comment '预约配送详情表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS RCFILE;