create database IF NOT EXISTS ds_tubobo_express;
use ds_tubobo_express
create table bas_storeentity_init
(
storeId                      String                    comment "店铺ID",
storeName                    String                    comment "店铺名称",
storeInfoStatus              String                    comment "信息审核状态",
service                      string                    comment "所属服务商",
lastStoreStatus              String                    comment "保留上个门店状态(门店关闭申请会记录当前 storeStatus到本字段)",
storeStatus                  String                    comment "门店审核状态成功:SUCCESS 失败:FAIL 撤销:REVOKE 城市经理:CITY_BD_PASS运营小二:OPERATIONAL_STAFF_PASS 临时关闭:CLOSED已退出:QUIT",
areaNumType                  int                       comment "取件码模式 0:架排模式 1:数字模式",
storeType                    String                    comment "门店类型0:校园店 1:社区店 2:园区店",
storeSource                  String                    comment "门店来源0:自营1:加盟",
storeBusiness                String                    comment "门店经营业务0:快递背景代办点 1:个人创业,2:便利店,3:水果店,4:奶茶店",
storeArea                    String                    comment "门店面积",
expressCompanyList           array<map<string,string>> comment "开通快递公司列表",
storeCode                    String                    comment "门店编号",
storeManageName              String                    comment "门店联系人",
storePhone                   String                    comment "门店联系人电话",
telephone                    String                    comment "客服联系电话",
alipayAccount                String                    comment "支付宝账户",
provinceCode                 String                    comment "省code",
province                     String                    comment "省中文",
cityCode                     String                    comment "市code",
city                         String                    comment "市中文",
districtCode                 String                    comment "区code",
district                     String                    comment "区中文",
storeAddressDetail           String                    comment "详细地址",
longitude                    String                    comment "门店经度",
latitude                     String                    comment "门店纬度",
picUrlStore                  String                    comment "门店照片",     
picUrlLicense                String                    comment "营业执照",
picUrlOne                    String                    comment "末端网店证",
serviceTimeStart             String                    comment "开始营业时间",
serviceTimeEnd               String                    comment "结束营业时间",
pickUpType                   String                    comment "区间通知方式,默认0:微信+短信,1微信",
workFlowId                   String                    comment "工作流id",
enterGuideStatus             String                    comment "入驻流程状态0:入驻审核,1:签署协议,2:缴纳保证金,3:入驻成功,4:完成入驻流程",
paid                         String                    comment "是否支付押金1:未缴费,0:已缴费,-1:无需缴费",
accountId                    String                    comment "资金账户ID",
appointServiceOpened         String                    comment "是否开启预约配送功能",
applyContent                 String                    comment "预约配送服务申请内容",
applyDate                    Timestamp                 comment "预约配送服务申请时间",    
createDate                   Timestamp                 comment "创建时间",     
createBy                     String                    comment "创建者",
updateDate                   Timestamp                 comment "更新时间",
updateBy                     String                    comment "更新人",      
appointServiceFlowId         String                    comment "预约配送服务流ID",
appointServiceStatus         String                    comment "预约配送审核状态",
auditStatus                  String                    comment "审核状态,PROVIDE_SERVICE等",
auditType                    String                    comment "审核类型,闭店,开店,退出",
auditDate                    Timestamp                 comment "审核申请时间",
auditWorkFlowId              String                    comment "审核流ID",
auditFlag                    String                    comment "审核标志,发起流程时,设为流程节点+_INIT.比如:STORE_INIT,当审核过之后设为STORE_INIT_PROCESS,流程结束设为STORE_INIT_PROCESS_OVER"
)
comment '店铺信息表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS RCFILE;


create table bas_storeentity_idld
(
storeId                      String                    comment "店铺ID",
storeName                    String                    comment "店铺名称",
storeInfoStatus              String                    comment "信息审核状态",
service                      string                    comment "所属服务商",
lastStoreStatus              String                    comment "保留上个门店状态(门店关闭申请会记录当前 storeStatus到本字段)",
storeStatus                  String                    comment "门店审核状态成功:SUCCESS 失败:FAIL 撤销:REVOKE 城市经理:CITY_BD_PASS运营小二:OPERATIONAL_STAFF_PASS 临时关闭:CLOSED已退出:QUIT",
areaNumType                  int                       comment "取件码模式 0:架排模式 1:数字模式",
storeType                    String                    comment "门店类型0:校园店 1:社区店 2:园区店",
storeSource                  String                    comment "门店来源0:自营1:加盟",
storeBusiness                String                    comment "门店经营业务0:快递背景代办点 1:个人创业,2:便利店,3:水果店,4:奶茶店",
storeArea                    String                    comment "门店面积",
expressCompanyList           array<map<string,string>> comment "开通快递公司列表",
storeCode                    String                    comment "门店编号",
storeManageName              String                    comment "门店联系人",
storePhone                   String                    comment "门店联系人电话",
telephone                    String                    comment "客服联系电话",
alipayAccount                String                    comment "支付宝账户",
provinceCode                 String                    comment "省code",
province                     String                    comment "省中文",
cityCode                     String                    comment "市code",
city                         String                    comment "市中文",
districtCode                 String                    comment "区code",
district                     String                    comment "区中文",
storeAddressDetail           String                    comment "详细地址",
longitude                    String                    comment "门店经度",
latitude                     String                    comment "门店纬度",
picUrlStore                  String                    comment "门店照片",     
picUrlLicense                String                    comment "营业执照",
picUrlOne                    String                    comment "末端网店证",
serviceTimeStart             String                    comment "开始营业时间",
serviceTimeEnd               String                    comment "结束营业时间",
pickUpType                   String                    comment "区间通知方式,默认0:微信+短信,1微信",
workFlowId                   String                    comment "工作流id",
enterGuideStatus             String                    comment "入驻流程状态0:入驻审核,1:签署协议,2:缴纳保证金,3:入驻成功,4:完成入驻流程",
paid                         String                    comment "是否支付押金1:未缴费,0:已缴费,-1:无需缴费",
accountId                    String                    comment "资金账户ID",
appointServiceOpened         String                    comment "是否开启预约配送功能",
applyContent                 String                    comment "预约配送服务申请内容",
applyDate                    Timestamp                 comment "预约配送服务申请时间",    
createDate                   Timestamp                 comment "创建时间",     
createBy                     String                    comment "创建者",
updateDate                   Timestamp                 comment "更新时间",
updateBy                     String                    comment "更新人",      
appointServiceFlowId         String                    comment "预约配送服务流ID",
appointServiceStatus         String                    comment "预约配送审核状态",
auditStatus                  String                    comment "审核状态,PROVIDE_SERVICE等",
auditType                    String                    comment "审核类型,闭店,开店,退出",
auditDate                    Timestamp                 comment "审核申请时间",
auditWorkFlowId              String                    comment "审核流ID",
auditFlag                    String                    comment "审核标志,发起流程时,设为流程节点+_INIT.比如:STORE_INIT,当审核过之后设为STORE_INIT_PROCESS,流程结束设为STORE_INIT_PROCESS_OVER"
)
comment '店铺信息表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS RCFILE;

create table bas_storeentity_pd
(
storeId                      String                    comment "店铺ID",
storeName                    String                    comment "店铺名称",
storeInfoStatus              String                    comment "信息审核状态",
service                      string                    comment "所属服务商",
lastStoreStatus              String                    comment "保留上个门店状态(门店关闭申请会记录当前 storeStatus到本字段)",
storeStatus                  String                    comment "门店审核状态成功:SUCCESS 失败:FAIL 撤销:REVOKE 城市经理:CITY_BD_PASS运营小二:OPERATIONAL_STAFF_PASS 临时关闭:CLOSED已退出:QUIT",
areaNumType                  int                       comment "取件码模式 0:架排模式 1:数字模式",
storeType                    String                    comment "门店类型0:校园店 1:社区店 2:园区店",
storeSource                  String                    comment "门店来源0:自营1:加盟",
storeBusiness                String                    comment "门店经营业务0:快递背景代办点 1:个人创业,2:便利店,3:水果店,4:奶茶店",
storeArea                    String                    comment "门店面积",
expressCompanyList           array<map<string,string>> comment "开通快递公司列表",
storeCode                    String                    comment "门店编号",
storeManageName              String                    comment "门店联系人",
storePhone                   String                    comment "门店联系人电话",
telephone                    String                    comment "客服联系电话",
alipayAccount                String                    comment "支付宝账户",
provinceCode                 String                    comment "省code",
province                     String                    comment "省中文",
cityCode                     String                    comment "市code",
city                         String                    comment "市中文",
districtCode                 String                    comment "区code",
district                     String                    comment "区中文",
storeAddressDetail           String                    comment "详细地址",
longitude                    String                    comment "门店经度",
latitude                     String                    comment "门店纬度",
picUrlStore                  String                    comment "门店照片",     
picUrlLicense                String                    comment "营业执照",
picUrlOne                    String                    comment "末端网店证",
serviceTimeStart             String                    comment "开始营业时间",
serviceTimeEnd               String                    comment "结束营业时间",
pickUpType                   String                    comment "区间通知方式,默认0:微信+短信,1微信",
workFlowId                   String                    comment "工作流id",
enterGuideStatus             String                    comment "入驻流程状态0:入驻审核,1:签署协议,2:缴纳保证金,3:入驻成功,4:完成入驻流程",
paid                         String                    comment "是否支付押金1:未缴费,0:已缴费,-1:无需缴费",
accountId                    String                    comment "资金账户ID",
appointServiceOpened         String                    comment "是否开启预约配送功能",
applyContent                 String                    comment "预约配送服务申请内容",
applyDate                    Timestamp                 comment "预约配送服务申请时间",    
createDate                   Timestamp                 comment "创建时间",     
createBy                     String                    comment "创建者",
updateDate                   Timestamp                 comment "更新时间",
updateBy                     String                    comment "更新人",      
appointServiceFlowId         String                    comment "预约配送服务流ID",
appointServiceStatus         String                    comment "预约配送审核状态",
auditStatus                  String                    comment "审核状态,PROVIDE_SERVICE等",
auditType                    String                    comment "审核类型,闭店,开店,退出",
auditDate                    Timestamp                 comment "审核申请时间",
auditWorkFlowId              String                    comment "审核流ID",
auditFlag                    String                    comment "审核标志,发起流程时,设为流程节点+_INIT.比如:STORE_INIT,当审核过之后设为STORE_INIT_PROCESS,流程结束设为STORE_INIT_PROCESS_OVER"
)
comment '店铺信息表'
partitioned by (day string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS RCFILE;

use da_tubobo_express;
create table da_tubobo_express.bas_storeentity_and_ues_create_date
(
create_date                  String                    comment "时间",
storeId                      String                    comment "店铺ID",
storeName                    String                    comment "店铺名称",
storeInfoStatus              String                    comment "信息审核状态",
service                      string                    comment "所属服务商",
lastStoreStatus              String                    comment "保留上个门店状态(门店关闭申请会记录当前 storeStatus到本字段)",
storeStatus                  String                    comment "门店审核状态成功:SUCCESS 失败:FAIL 撤销:REVOKE 城市经理:CITY_BD_PASS运营小二:OPERATIONAL_STAFF_PASS 临时关闭:CLOSED已退出:QUIT",
areaNumType                  int                       comment "取件码模式 0:架排模式 1:数字模式",
storeType                    String                    comment "门店类型0:校园店 1:社区店 2:园区店",
storeSource                  String                    comment "门店来源0:自营1:加盟",
storeBusiness                String                    comment "门店经营业务0:快递背景代办点 1:个人创业,2:便利店,3:水果店,4:奶茶店",
storeArea                    String                    comment "门店面积",
expressCompanyList           array<map<string,string>> comment "开通快递公司列表",
storeCode                    String                    comment "门店编号",
storeManageName              String                    comment "门店联系人",
storePhone                   String                    comment "门店联系人电话",
telephone                    String                    comment "客服联系电话",
alipayAccount                String                    comment "支付宝账户",
provinceCode                 String                    comment "省code",
province                     String                    comment "省中文",
cityCode                     String                    comment "市code",
city                         String                    comment "市中文",
districtCode                 String                    comment "区code",
district                     String                    comment "区中文",
storeAddressDetail           String                    comment "详细地址",
longitude                    String                    comment "门店经度",
latitude                     String                    comment "门店纬度",
picUrlStore                  String                    comment "门店照片",     
picUrlLicense                String                    comment "营业执照",
picUrlOne                    String                    comment "末端网店证",
serviceTimeStart             String                    comment "开始营业时间",
serviceTimeEnd               String                    comment "结束营业时间",
pickUpType                   String                    comment "区间通知方式,默认0:微信+短信,1微信",
workFlowId                   String                    comment "工作流id",
enterGuideStatus             String                    comment "入驻流程状态0:入驻审核,1:签署协议,2:缴纳保证金,3:入驻成功,4:完成入驻流程",
paid                         String                    comment "是否支付押金1:未缴费,0:已缴费,-1:无需缴费",
accountId                    String                    comment "资金账户ID",
appointServiceOpened         String                    comment "是否开启预约配送功能",
applyContent                 String                    comment "预约配送服务申请内容",
applyDate                    Timestamp                 comment "预约配送服务申请时间",    
createDate                   Timestamp                 comment "创建时间",     
createBy                     String                    comment "创建者",
updateDate                   Timestamp                 comment "更新时间",
updateBy                     String                    comment "更新人",      
appointServiceFlowId         String                    comment "预约配送服务流ID",
appointServiceStatus         String                    comment "预约配送审核状态",
auditStatus                  String                    comment "审核状态,PROVIDE_SERVICE等",
auditType                    String                    comment "审核类型,闭店,开店,退出",
auditDate                    Timestamp                 comment "审核申请时间",
auditWorkFlowId              String                    comment "审核流ID",
auditFlag                    String                    comment "审核标志,发起流程时,设为流程节点+_INIT.比如:STORE_INIT,当审核过之后设为STORE_INIT_PROCESS,流程结束设为STORE_INIT_PROCESS_OVER"
)
comment '店铺信息表'
partitioned by (day string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS RCFILE;