create database IF NOT EXISTS ds_tubobo_merchant;
use  ds_tubobo_merchant;
CREATE TABLE bas_tubobo_merchant_info_idld
(
id                      string comment '序列ID',
merchant_status         string COMMENT '商家认证状态',
merchant_name           string COMMENT '商家名称',
phone                   string COMMENT '电话号码',
real_name               string COMMENT '姓名',
id_card_no              string COMMENT '身份证号',
address_province        string COMMENT '地址详情',
address_city            string COMMENT '地址缩略',
address_district        string COMMENT '地址名称',
avatar_url              string COMMENT '头像地址',
id_card_front_image_url string COMMENT '身份证正面',
id_card_back_image_url  string COMMENT '身份证反面',
longitude               string COMMENT '经度',
latitude                string COMMENT '纬度',
apply_date              string COMMENT '申请时间',
verify_date             string COMMENT '验证时间',
create_by               string COMMENT '创建者',
create_date             string COMMENT '创建时间',
update_by               string COMMENT '更新者',
update_date             string COMMENT '更新时间',
remarks                 string COMMENT '备注信息',
del_flag                int    COMMENT '删除标记',
user_id                 string comment '商家ID',
account_id              string comment '商家资金账户ID',
address_street          string comment '街道地址',
address_detail          string comment '详细地址',
pay_id                  int    comment '支付ID',
address_room_no         string comment '地址房间号',
shop_image_url          string COMMENT '店铺照片',
identify_type           string COMMENT '认证类型',
enable_pwd_free         string COMMENT '是否开启免密支付',
has_set_pay_pwd         string COMMENT '是否设置过支付密码',
consignor_status        string COMMENT '货主认证状态',
shop_image_url2         string comment '店铺相片路径',
shop_licences_img_url   string comment '营业证相片路径',
bd_code                 string comment '邮编',
address_ad_code         string comment '商家地址邮编',
reason                  string comment '不合格理由',
bd_update_date          string COMMENT 'bd邀请码绑定时间',
provider_id             int    COMMENT '所属服务商ID',
hygiene_license         string COMMENT '卫生许可证',
mer_type_id             int    COMMENT '商家类型id',
shop_licences_no        string COMMENT '商家营业执照号'
)
COMMENT '商家信息表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'  STORED AS TEXTFILE;

CREATE TABLE bas_tubobo_merchant_info_pd
(
id                      string comment '序列ID',
merchant_status         string COMMENT '商家认证状态',
merchant_name           string COMMENT '商家名称',
phone                   string COMMENT '电话号码',
real_name               string COMMENT '姓名',
id_card_no              string COMMENT '身份证号',
address_province        string COMMENT '地址详情',
address_city            string COMMENT '地址缩略',
address_district        string COMMENT '地址名称',
avatar_url              string COMMENT '头像地址',
id_card_front_image_url string COMMENT '身份证正面',
id_card_back_image_url  string COMMENT '身份证反面',
longitude               string COMMENT '经度',
latitude                string COMMENT '纬度',
apply_date              string COMMENT '申请时间',
verify_date             string COMMENT '验证时间',
create_by               string COMMENT '创建者',
create_date             string COMMENT '创建时间',
update_by               string COMMENT '更新者',
update_date             string COMMENT '更新时间',
remarks                 string COMMENT '备注信息',
del_flag                int    COMMENT '删除标记',
user_id                 string comment '商家ID',
account_id              string comment '商家资金账户ID',
address_street          string comment '街道地址',
address_detail          string comment '详细地址',
pay_id                  int    comment '支付ID',
address_room_no         string comment '地址房间号',
shop_image_url          string COMMENT '店铺照片',
identify_type           string COMMENT '认证类型',
enable_pwd_free         string COMMENT '是否开启免密支付',
has_set_pay_pwd         string COMMENT '是否设置过支付密码',
consignor_status        string COMMENT '货主认证状态',
shop_image_url2         string comment '店铺相片路径',
shop_licences_img_url   string comment '营业证相片路径',
bd_code                 string comment '邮编',
address_ad_code         string comment '商家地址邮编',
reason                  string comment '不合格理由',
bd_update_date          string COMMENT 'bd邀请码绑定时间',
provider_id             int    COMMENT '所属服务商ID',
hygiene_license         string COMMENT '卫生许可证',
mer_type_id             int    COMMENT '商家类型id',
shop_licences_no        string COMMENT '商家营业执照号'
)
COMMENT '商家信息表'
partitioned by (day string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'  STORED AS RCFILE;