create database  IF NOT EXISTS ds_tubobo_merchant;
use  ds_tubobo_merchant;
CREATE TABLE bas_tubobo_order_idld
(
id                        int    COMMENT '序列ID',
order_status              string COMMENT '订单状态',
order_no                  string COMMENT '订单编号',
order_type                string COMMENT '订单类型',
pay_amount                int    COMMENT '支付金额',
delivery_fee              int    COMMENT '配送费',
tip_fee                   int    COMMENT '小费',
pay_status                string COMMENT '支付状态',
pay_method                string COMMENT '支付方法',
pay_time                  string COMMENT '付款时间',
order_time                string COMMENT '下单时间',
cancel_time               string COMMENT '取消时间',
grab_order_time           string COMMENT '接单时间',
grab_item_time            string COMMENT '取货时间',
finish_order_time         string COMMENT '订单完成时间',
user_id                   string COMMENT '寄货人id',
sender_name               string COMMENT '寄货人姓名',
receiver_name             string COMMENT '收货人姓名',
receiver_phone            string COMMENT '收货人电话',
receiver_longitude        string COMMENT '收货人经度',
receiver_latitude         string COMMENT '收货人纬度',
rider_id                  string COMMENT '骑手id',
rider_name                string COMMENT '骑手姓名',
rider_phone               string COMMENT '骑手电话',
create_by                 string COMMENT '创建者',
create_date               string COMMENT '创建时间',
update_date               string COMMENT '更新时间',
del_flag                  int    COMMENT '删除标记',
receiver_address_name     string comment '收货人地址',
receiver_address_province string COMMENT '收货人地址',
receiver_address_street   string COMMENT '收货人街道',
receiver_address_detail   string COMMENT '收货人详细地址',
receiver_address_city     string COMMENT '收货人城市',
receiver_address_district string COMMENT '收货人所在的区',
pay_id                    string COMMENT '支付ID',
delivery_distance         string COMMENT '投递距离',
receiver_address_room_no  string COMMENT '收货人房间号',
expect_finish_time        string COMMENT '预计送达时间',
rated_flag                string COMMENT '是否已评价',
origin_order_id           string COMMENT '第三方平台原始订单号',
origin_order_view_id      string COMMENT '第三方平台原始展示订单号',
platform_code             string COMMENT '第三方平台原始展示订单号',
weather_over_fee          int    COMMENT '天气溢价费',
peek_over_fee             int    COMMENT '高峰溢价费',
sender_adcode             string COMMENT '发货人区域编码',
unsettled_status          string COMMENT '未妥投状态',
unsettled_time            string COMMENT '未妥投时间',
short_message             string COMMENT '是否短信通知用户',
provider_id               int    COMMENT '所属服务商ID',
order_feature             string COMMENT '订单特征:RIDER_CANCEL_RESEND 骑手取消重发单'
)
COMMENT '商家订单表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'  STORED AS TEXTFILE;

CREATE TABLE bas_tubobo_order_init
(
id                        int    COMMENT '序列ID',
order_status              string COMMENT '订单状态',
order_no                  string COMMENT '订单编号',
order_type                string COMMENT '订单类型',
pay_amount                int    COMMENT '支付金额',
delivery_fee              int    COMMENT '配送费',
tip_fee                   int    COMMENT '小费',
pay_status                string COMMENT '支付状态',
pay_method                string COMMENT '支付方法',
pay_time                  string COMMENT '付款时间',
order_time                string COMMENT '下单时间',
cancel_time               string COMMENT '取消时间',
grab_order_time           string COMMENT '接单时间',
grab_item_time            string COMMENT '取货时间',
finish_order_time         string COMMENT '订单完成时间',
user_id                   string COMMENT '寄货人id',
sender_name               string COMMENT '寄货人姓名',
receiver_name             string COMMENT '收货人姓名',
receiver_phone            string COMMENT '收货人电话',
receiver_longitude        string COMMENT '收货人经度',
receiver_latitude         string COMMENT '收货人纬度',
rider_id                  string COMMENT '骑手id',
rider_name                string COMMENT '骑手姓名',
rider_phone               string COMMENT '骑手电话',
create_by                 string COMMENT '创建者',
create_date               string COMMENT '创建时间',
update_date               string COMMENT '更新时间',
del_flag                  int    COMMENT '删除标记',
receiver_address_name     string comment '收货人地址',
receiver_address_province string COMMENT '收货人地址',
receiver_address_street   string COMMENT '收货人街道',
receiver_address_detail   string COMMENT '收货人详细地址',
receiver_address_city     string COMMENT '收货人城市',
receiver_address_district string COMMENT '收货人所在的区',
pay_id                    string COMMENT '支付ID',
delivery_distance         string COMMENT '投递距离',
receiver_address_room_no  string COMMENT '收货人房间号',
expect_finish_time        string COMMENT '预计送达时间',
rated_flag                string COMMENT '是否已评价',
origin_order_id           string COMMENT '第三方平台原始订单号',
origin_order_view_id      string COMMENT '第三方平台原始展示订单号',
platform_code             string COMMENT '第三方平台原始展示订单号',
weather_over_fee          int    COMMENT '天气溢价费',
peek_over_fee             int    COMMENT '高峰溢价费',
sender_adcode             string COMMENT '发货人区域编码',
unsettled_status          string COMMENT '未妥投状态',
unsettled_time            string COMMENT '未妥投时间',
short_message             string COMMENT '是否短信通知用户',
provider_id               int    COMMENT '所属服务商ID',
order_feature             string COMMENT '订单特征:RIDER_CANCEL_RESEND 骑手取消重发单'
)
COMMENT '商家订单表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'  STORED AS TEXTFILE;


CREATE TABLE bas_tubobo_order_pd
(
id                        int    COMMENT '序列ID',
order_status              string COMMENT '订单状态',
order_no                  string COMMENT '订单编号',
order_type                string COMMENT '订单类型',
pay_amount                int    COMMENT '支付金额',
delivery_fee              int    COMMENT '配送费',
tip_fee                   int    COMMENT '小费',
pay_status                string COMMENT '支付状态',
pay_method                string COMMENT '支付方法',
pay_time                  string COMMENT '付款时间',
order_time                string COMMENT '下单时间',
cancel_time               string COMMENT '取消时间',
grab_order_time           string COMMENT '接单时间',
grab_item_time            string COMMENT '取货时间',
finish_order_time         string COMMENT '订单完成时间',
user_id                   string COMMENT '寄货人id',
sender_name               string COMMENT '寄货人姓名',
receiver_name             string COMMENT '收货人姓名',
receiver_phone            string COMMENT '收货人电话',
receiver_longitude        string COMMENT '收货人经度',
receiver_latitude         string COMMENT '收货人纬度',
rider_id                  string COMMENT '骑手id',
rider_name                string COMMENT '骑手姓名',
rider_phone               string COMMENT '骑手电话',
create_by                 string COMMENT '创建者',
create_date               string COMMENT '创建时间',
update_date               string COMMENT '更新时间',
del_flag                  int    COMMENT '删除标记',
receiver_address_name     string comment '收货人地址',
receiver_address_province string COMMENT '收货人地址',
receiver_address_street   string COMMENT '收货人街道',
receiver_address_detail   string COMMENT '收货人详细地址',
receiver_address_city     string COMMENT '收货人城市',
receiver_address_district string COMMENT '收货人所在的区',
pay_id                    string COMMENT '支付ID',
delivery_distance         string COMMENT '投递距离',
receiver_address_room_no  string COMMENT '收货人房间号',
expect_finish_time        string COMMENT '预计送达时间',
rated_flag                string COMMENT '是否已评价',
origin_order_id           string COMMENT '第三方平台原始订单号',
origin_order_view_id      string COMMENT '第三方平台原始展示订单号',
platform_code             string COMMENT '第三方平台原始展示订单号',
weather_over_fee          int    COMMENT '天气溢价费',
peek_over_fee             int    COMMENT '高峰溢价费',
sender_adcode             string COMMENT '发货人区域编码',
unsettled_status          string COMMENT '未妥投状态',
unsettled_time            string COMMENT '未妥投时间',
short_message             string COMMENT '是否短信通知用户',
provider_id               int    COMMENT '所属服务商ID',
order_feature             string COMMENT '订单特征:RIDER_CANCEL_RESEND 骑手取消重发单'
)
COMMENT '商家订单表'
partitioned by (day string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'  STORED AS RCFILE;