create database  IF NOT EXISTS ds_tubobo_merchant
use  ds_tubobo_merchant;
CREATE TABLE bas_tubobo_order_detail_idld
(
id                                int    COMMENT '序列ID',
order_no                          string COMMENT '订单编号',
order_remark                      string COMMENT '订单备注',
user_id                           string COMMENT '寄货人id',
sender_phone                      int    COMMENT '寄货人电话',
sender_address                    string COMMENT '寄货人地址',
sender_longitude                  string COMMENT '寄货人经度',
sender_latitude                   string COMMENT '寄货人纬度',
dispatch_radius                   string COMMENT '分派半径',
create_date                       string COMMENT '创建时间',
update_date                       string COMMENT '更新时间',
del_flag                          int    COMMENT '删除标记',
receiver_address_name             string COMMENT '收货人姓名',
sender_address_detail             string COMMENT '寄货人详情',
sender_address_province           string COMMENT '寄货人所在城市',
sender_address_name               string COMMENT '寄货人姓名',
sender_address_city               string COMMENT '寄货人所在城市',
sender_address_district           string COMMENT '寄货人所在区',
sender_address_street             string COMMENT '寄货人街道',
sender_address_room_no            string COMMENT '寄货人房间号',
cancel_reason                     string COMMENT '取消原因',
expired_minute                    string COMMENT '超时时间',
expired_compensation              string COMMENT '超时补偿',
wait_pick_cancel_type             string COMMENT '已接单状态下取消订单原因',
cancel_fine                       string COMMENT '订单取消罚款金额',
cancel_compensation               string COMMENT '订单取消赔付金额',
pickup_distance                   string COMMENT '取货距离',
unsettled_reason                  string COMMENT '未妥投原因',
mer_message                       string COMMENT '未妥投确认消息',
resend_target_no                  string COMMENT '重发订单-来源单号',
platform_fee                      string COMMENT '平台抽成',
rider_fee                         string COMMENT '骑手real配送费',
cancel_source_delivery_fee        string COMMENT '取消订单原发配送费',
cancel_source_delivery_subsidy    string COMMENT '取消订单原骑手补贴金额',
cancel_source_order_no            string COMMENT '取消订单原单号'
)
COMMENT '商家订单详情表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'  STORED AS TEXTFILE;

CREATE TABLE bas_tubobo_order_detail_init
(
id                                int    COMMENT '序列ID',
order_no                          string COMMENT '订单编号',
order_remark                      string COMMENT '订单备注',
user_id                           string COMMENT '寄货人id',
sender_phone                      int    COMMENT '寄货人电话',
sender_address                    string COMMENT '寄货人地址',
sender_longitude                  string COMMENT '寄货人经度',
sender_latitude                   string COMMENT '寄货人纬度',
dispatch_radius                   string COMMENT '分派半径',
create_date                       string COMMENT '创建时间',
update_date                       string COMMENT '更新时间',
del_flag                          int    COMMENT '删除标记',
receiver_address_name             string COMMENT '收货人姓名',
sender_address_detail             string COMMENT '寄货人详情',
sender_address_province           string COMMENT '寄货人所在城市',
sender_address_name               string COMMENT '寄货人姓名',
sender_address_city               string COMMENT '寄货人所在城市',
sender_address_district           string COMMENT '寄货人所在区',
sender_address_street             string COMMENT '寄货人街道',
sender_address_room_no            string COMMENT '寄货人房间号',
cancel_reason                     string COMMENT '取消原因',
expired_minute                    string COMMENT '超时时间',
expired_compensation              string COMMENT '超时补偿',
wait_pick_cancel_type             string COMMENT '已接单状态下取消订单原因',
cancel_fine                       string COMMENT '订单取消罚款金额',
cancel_compensation               string COMMENT '订单取消赔付金额',
pickup_distance                   string COMMENT '取货距离',
unsettled_reason                  string COMMENT '未妥投原因',
mer_message                       string COMMENT '未妥投确认消息',
resend_target_no                  string COMMENT '重发订单-来源单号',
platform_fee                      string COMMENT '平台抽成',
rider_fee                         string COMMENT '骑手real配送费',
cancel_source_delivery_fee        string COMMENT '取消订单原发配送费',
cancel_source_delivery_subsidy    string COMMENT '取消订单原骑手补贴金额',
cancel_source_order_no            string COMMENT '取消订单原单号'
)
COMMENT '商家订单详情表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'  STORED AS TEXTFILE;

CREATE TABLE bas_tubobo_order_detail_pd
(
id                                int    COMMENT '序列ID',
order_no                          string COMMENT '订单编号',
order_remark                      string COMMENT '订单备注',
user_id                           string COMMENT '寄货人id',
sender_phone                      int    COMMENT '寄货人电话',
sender_address                    string COMMENT '寄货人地址',
sender_longitude                  string COMMENT '寄货人经度',
sender_latitude                   string COMMENT '寄货人纬度',
dispatch_radius                   string COMMENT '分派半径',
create_date                       string COMMENT '创建时间',
update_date                       string COMMENT '更新时间',
del_flag                          int    COMMENT '删除标记',
receiver_address_name             string COMMENT '收货人姓名',
sender_address_detail             string COMMENT '寄货人详情',
sender_address_province           string COMMENT '寄货人所在城市',
sender_address_name               string COMMENT '寄货人姓名',
sender_address_city               string COMMENT '寄货人所在城市',
sender_address_district           string COMMENT '寄货人所在区',
sender_address_street             string COMMENT '寄货人街道',
sender_address_room_no            string COMMENT '寄货人房间号',
cancel_reason                     string COMMENT '取消原因',
expired_minute                    string COMMENT '超时时间',
expired_compensation              string COMMENT '超时补偿',
wait_pick_cancel_type             string COMMENT '已接单状态下取消订单原因',
cancel_fine                       string COMMENT '订单取消罚款金额',
cancel_compensation               string COMMENT '订单取消赔付金额',
pickup_distance                   string COMMENT '取货距离',
unsettled_reason                  string COMMENT '未妥投原因',
mer_message                       string COMMENT '未妥投确认消息',
resend_target_no                  string COMMENT '重发订单-来源单号',
platform_fee                      string COMMENT '平台抽成',
rider_fee                         string COMMENT '骑手real配送费',
cancel_source_delivery_fee        string COMMENT '取消订单原发配送费',
cancel_source_delivery_subsidy    string COMMENT '取消订单原骑手补贴金额',
cancel_source_order_no            string COMMENT '取消订单原单号'
)
COMMENT '商家订单详情表'
partitioned by (day string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'  STORED AS RCFILE;